version: '3.8'

services:

  app:
    build: ./app
    ports:
      - 8000:8000
    volumes:
      - static:/vol/web
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - STATIC_ROOT=/vol/web/static
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on: 
      - db
    container_name: app

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static:/vol/web
    environment:
      - VIRTUAL_HOST=example.org,www.example.org
    depends_on:
      - app
    container_name: nginx

  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - db:/var/lib/mysql
    container_name: mariadb

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports: 
      - 8001:80
    environment:
      - PMA_HOST=db
      - VIRTUAL_HOST=pma.example.org

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    privileged: true
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  static:
  db:
