version: '3.8'

services:

  web:
    build: ./app
    ports:
      - 8000:8000
    volumes:
      - static:/vol/web
    env_file: 
      - ./.env
    depends_on: 
      - db
    container_name: rnames_web_prod

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static:/vol/web
    depends_on:
      - web
    container_name: rnames_nginx_prod

  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    command:
      - "--character-set-server=utf8mb4"
    volumes:
      - db:/var/lib/mysql
    container_name: rnames_db_prod

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports: 
      - 8001:80
    environment:
      - PMA_HOST=db
    container_name: rnames_phpmyadmin_prod

volumes:
  static:
  db:
